# Generated by Django 4.2.7 on 2023-11-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='image_url',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
