# Generated by Django 4.2.7 on 2023-11-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=20)),
                ('movieimg', models.ImageField(blank=True, null=True, upload_to='images')),
                ('movieopendate', models.DateField()),
                ('moviedirector', models.CharField(max_length=20)),
                ('mocieactor', models.CharField(max_length=20)),
                ('moviegenre', models.CharField(max_length=20)),
                ('movieinfo', models.CharField(max_length=30)),
            ],
        ),
    ]
