# Generated by Django 4.2.7 on 2023-11-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_moviereserve_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereserve',
            name='img_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movie.movieinfo'),
        ),
    ]
