# Generated by Django 4.2.7 on 2023-11-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movieinfo_id_alter_movieinfo_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='image_url',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
