# Generated by Django 4.2.7 on 2023-11-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movieinfo_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReserve',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('movie_date', models.CharField(max_length=15)),
                ('reserve_date', models.CharField(max_length=15)),
                ('selected_seat', models.CharField(max_length=100)),
                ('selected_theater', models.CharField(max_length=100)),
            ],
        ),
    ]
