# Generated by Django 4.2.7 on 2023-11-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_moviereserve_img_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereserve',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
