# Generated by Django 4.2.7 on 2023-11-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_moviereserve_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereserve',
            name='payMoney',
            field=models.CharField(default='', max_length=100),
        ),
    ]
