# Generated by Django 4.2.7 on 2023-11-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_moviereserve_paymoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereserve',
            name='img_code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movieinfo'),
        ),
        migrations.AlterField(
            model_name='moviereserve',
            name='user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.profile'),
        ),
    ]
