# Generated by Django 4.2.7 on 2023-11-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_moviereserve_img_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereserve',
            name='running_time',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
