# Generated by Django 4.2.7 on 2023-11-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_profile_email_profile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
