# Generated by Django 4.2.7 on 2023-11-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phoneNumber',
        ),
    ]
